2023-03-30 09:18:42	INFO	::casa	
2023-03-30 09:18:44	INFO	::casa	Python version 3.8.16
2023-03-30 09:18:44	INFO	::casa	CASA Version MODULAR 6.5.3.28
2023-03-30 09:18:44	INFO	::casa	Can't import casatelemetry module.
2023-03-30 09:18:47	INFO	listobs::::casa	##########################################
2023-03-30 09:18:47	INFO	listobs::::casa	##### Begin Task: listobs            #####
2023-03-30 09:18:47	INFO	listobs::::casa	listobs( vis='/DATA/CARINA_3/kel334/19A-056/19A-056.sb37163380.eb37257903.58741.80710626158/19A-056.sb37163380.eb37257903.58741.80710626158_hanning.ms', selectdata=True, spw='', field='', antenna='', uvrange='', timerange='', correlation='', scan='', intent='', feed='', array='', observation='', verbose=True, listfile='', listunfl=False, cachesize=50.0, overwrite=False )
2023-03-30 09:18:48	SEVERE	listobs::ms::open	Exception Reported: FilebufIO::readBlock - incorrect number of bytes read for file /DATA/CARINA_3/kel334/19A-056/19A-056.sb37163380.eb37257903.58741.80710626158/19A-056.sb37163380.eb37257903.58741.80710626158_hanning.ms/table.dat
2023-03-30 09:18:48	SEVERE	listobs::::casa	Task listobs raised an exception of class RuntimeError with the following message: FilebufIO::readBlock - incorrect number of bytes read for file /DATA/CARINA_3/kel334/19A-056/19A-056.sb37163380.eb37257903.58741.80710626158/19A-056.sb37163380.eb37257903.58741.80710626158_hanning.ms/table.dat
2023-03-30 09:18:48	INFO	listobs::::casa	Task listobs complete. Start time: 2023-03-30 20:18:47.340401 End time: 2023-03-30 20:18:47.633019
2023-03-30 09:18:48	INFO	listobs::::casa	##### End Task: listobs              #####
2023-03-30 09:18:48	INFO	listobs::::casa	##########################################
2023-03-30 09:18:55	SEVERE	msmetadata_cmpt.cc::open	Exception Reported: FilebufIO::readBlock - incorrect number of bytes read for file /DATA/CARINA_3/kel334/19A-056/19A-056.sb37163380.eb37257903.58741.80710626158/19A-056.sb37163380.eb37257903.58741.80710626158_hanning.ms/table.dat
